name = "LSpec"
version = "2.1.0"
defaultTargets = [
  "LSpec",
  "lspec-discover",
]
testDriver = "Test.Main"
# precompileModules = true

[build]
lean_opts = ["-g", "-O0"]

# [[lean_lib]]
# name = "GetOpt"

# [[lean_lib]]
# name = "Polyfill"

# [[lean_lib]]
# name = "LUnit"

[[lean_lib]]
name = "LSpec"

[[lean_exe]]
name = "lspec-discover"
root = "LSpec.Discover.Main"
needs = ["LSpec"]

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "Test.Main"
buildType = "debug"

# [[require]]
# name = "mathlib"
# scope = "leanprover-community"
# rev = "059a5bcfe2f022fdcc04b1f294252566da9c21a2"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.22.0-rc4"

[[require]]
name = "Cli"
git = "https://github.com/leoslf/lean4-cli"
rev = "main" # "286f67902bbb5b8cbb1550c471feec44121150de"

[[require]]
name = "Printf"
git = "https://github.com/leoslf/printf.lean"
rev = "master" # "0c13a4baf6e23a9a94742211eb11b257f036a750"

[[require]]
name = "Free"
git = "https://github.com/leoslf/free.lean"
rev = "master" # "39e99349f957ea406000fbf0105309b4444b8a8a"

[[require]]
name = "Concurrency"
git = "https://github.com/leoslf/concurrency.lean"
rev = "master" # "f3440dae0a76204f5b7e56c8b8de3d09848fe631"
