name = "LSpec"
version = "2.1.0"
defaultTargets = [
  "LSpec",
  "lspec-discover",
]
testDriver = "Test.Main"

[build]
lean_opts = ["-g", "-O0"]

[[lean_lib]]
name = "GetOpt"

[[lean_lib]]
name = "Polyfill"

[[lean_lib]]
name = "Console"

[[lean_lib]]
name = "LUnit"

[[lean_lib]]
name = "LSpec"

[[lean_exe]]
name = "lspec-discover"
root = "LSpec.Discover.Main"
needs = ["LSpec"]

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "Test.Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "059a5bcfe2f022fdcc04b1f294252566da9c21a2"

[[require]]
name = "Cli"
git = "https://github.com/leoslf/lean4-cli"
rev = "286f67902bbb5b8cbb1550c471feec44121150de"

[[require]]
name = "Printf"
git = "https://github.com/leoslf/printf.lean"
rev = "eb65b3563d92e84a54f8fe97c3cc0615700b665e"

[[require]]
name = "Free"
git = "https://github.com/leoslf/free.lean"
rev = "39e99349f957ea406000fbf0105309b4444b8a8a"

[[require]]
name = "Concurrency"
git = "https://github.com/leoslf/concurrency.lean"
rev = "f3440dae0a76204f5b7e56c8b8de3d09848fe631"
